apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-handler
  template:
    metadata:
      labels:
        app: db-handler
    spec:
      initContainers:
        - command:
            - /bin/sh
            - -c
            - cp /root/dev/db/* root/
          image: busybox
          imagePullPolicy: Always
          name: configmap-copy
          volumeMounts:
            - mountPath: /root/dev/db
              name: soa-configmap1
            - mountPath: /root/
              name: config
      volumes:
        - emptyDir: {}
          name: config
        - configMap:
            defaultMode: 420
            name: soa-config-ok
          name: soa-configmap1
      containers:
        - name: db-container
          image: db-handler:v1
          tty: true
          stdin: true
          imagePullPolicy: IfNotPresent #which means nodes will use an existing image rather than pull a new one
          volumeMounts:
          - mountPath: /root
            name: config
          - mountPath: /root/dev/db
            name: soa-configmap1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beverage-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bev-deployment
  template:
    metadata:
      labels:
        app: bev-deployment
    spec:
      containers:
        - name: beverage-container
          image: beverage:v1
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mgmt-deployment
  template:
    metadata:
      labels:
        app: mgmt-deployment
    spec:
      containers:
        - name: management-container
          image: management:v1
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: default
spec:
  selector:
    app: db-handler
  ports:
  - port: 9999
    targetPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: beverage-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: bev-deployment
  ports:
   - protocol: TCP
     port: 8081
     targetPort: 8080
     nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: management-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: mgmt-deployment
  ports:
   - protocol: TCP
     port: 8091
     targetPort: 8090
     nodePort: 30002